const crypto = require("crypto");

const ORIGIN = "https://app.blackbox.ai";
const UA = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36";
const FALLBACK_VALIDATED = "a38f5889-8fef-46d4-8ede-bf4668b6a9bb";
const ANCHOR = /([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})/;

const SYSTEM = `You are KRY AI, a capable assistant. Be helpful, clear, and thorough.

When the user asks you to create or generate a file (code, script, config, HTML, JSON, CSV, markdown, etc), ALWAYS wrap it using this exact format:

\`\`\`artifact:filename.ext
file content here
\`\`\`

Examples:
\`\`\`artifact:hello.py
print("Hello world")
\`\`\`

\`\`\`artifact:index.html
<!DOCTYPE html><html>...</html>
\`\`\`

\`\`\`artifact:data.json
{"key": "value"}
\`\`\`

Only use artifact blocks for actual files the user wants to download. Regular code examples that are just illustrations use normal markdown code blocks.

When file contents are provided, analyze them thoroughly and answer the user's question about them.

Wrap your final reply between <answer> and </answer> tags.`;

const OPEN_TAG = /^(?:<answer>|answer>|nswer>|swer>|wer>|er>|r>|>)\s*/;

let cachedValidated = FALLBACK_VALIDATED;
const POW_DIFFICULTY = 5;
const challenges = new Map();
const rateLimits = new Map();
const bannedIPs = new Set();
const requestLog = [];
const MAX_REQUEST_LOG = 1000;
const MAX_PROMPT_LENGTH = 10000;
const MAX_FILE_SIZE = 500000;
const MAX_HISTORY_LENGTH = 20;
const ALLOWED_MODELS = new Set(["blackbox", "gemini", "auto"]);

function randomId(len = 7) {
    const chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";
    let s = "";
    for (let i = 0; i < len; i++) s += chars[Math.floor(Math.random() * chars.length)];
    return s;
}

function isRejected(raw) {
    return /Generated by BLACKBOX\.AI|not upgraded your account/i.test(raw);
}

function sanitizeInput(str) {
    if (typeof str !== "string") return "";
    return str.replace(/[\x00-\x08\x0B\x0C\x0E-\x1F\x7F]/g, "").trim();
}

function parseResponse(raw) {
    const thinkParts = [];
    let body = raw.replace(/<think>([\s\S]*?)<\/think>/g, (_, t) => {
        thinkParts.push(t.trim());
        return "";
    });
    const end = body.indexOf("</answer>");
    if (end !== -1) body = body.slice(0, end);
    body = body.trimStart().replace(OPEN_TAG, "").trim();

    const artifacts = [];
    body = body.replace(/```artifact:([^\n]+)\n([\s\S]*?)```/g, (_, filename, content) => {
        const safeFilename = filename.replace(/[^a-zA-Z0-9.\-_]/g, "").slice(0, 50);
        artifacts.push({ filename: safeFilename, content: content.trim() });
        return `[[ARTIFACT_${artifacts.length - 1}]]`;
    });

    return { text: body.trim(), think: thinkParts.join("\n\n").trim() || null, artifacts };
}

async function fetchValidated() {
    const headers = { "user-agent": UA };
    try {
        const html = await fetch(`${ORIGIN}/`, { headers }).then(r => r.text()).catch(() => "");
        const chunks = [...new Set([...html.matchAll(/\/_next\/static\/[^"]+\.js/g)].map(m => m[0]))];
        for (const chunk of chunks) {
            try {
                const js = await fetch(`${ORIGIN}${chunk}`, { headers }).then(r => r.text());
                const match = js.match(ANCHOR);
                if (match && match[1]) return match[1];
            } catch (e) { continue; }
        }
    } catch (e) {}
    return null;
}

function buildBBPayload(messages, validated, options = {}) {
    return {
        messages,
        id: messages[messages.length - 1].id,
        userSelectedAgent: "VscodeAgent",
        userSelectedModel: null,
        maxTokens: 4096,
        validated,
        clickedForceWebSearch: options.webSearch || false,
        webSearchModeOption: { autoMode: !options.webSearch, webMode: options.webSearch, offlineMode: false },
        codeModelMode: true,
        isPremium: false
    };
}

async function bbRequest(payload) {
    const res = await fetch(`${ORIGIN}/api/chat`, {
        method: "POST",
        headers: {
            "content-type": "application/json",
            "origin": ORIGIN,
            "referer": `${ORIGIN}/chat`,
            "user-agent": UA
        },
        body: JSON.stringify(payload)
    });
    return res.text();
}

async function blackboxChat(prompt, options = {}) {
    const history = Array.isArray(options.history) ? options.history.slice(0, MAX_HISTORY_LENGTH) : [];
    const userMsg = { id: randomId(), role: "user", content: String(prompt) };
    const wrapped = [{ id: randomId(), role: "system", content: SYSTEM }, ...history, userMsg];

    let raw = await bbRequest(buildBBPayload(wrapped, cachedValidated, options));

    if (isRejected(raw)) {
        const fresh = await fetchValidated();
        if (fresh && fresh !== cachedValidated) {
            cachedValidated = fresh;
            raw = await bbRequest(buildBBPayload(wrapped, cachedValidated, options));
        }
    }

    if (isRejected(raw)) return { ok: false, error: "Service rejected request" };

    const { text, think, artifacts } = parseResponse(raw);
    return {
        ok: true, text, think, artifacts,
        history: [...history, userMsg, { id: randomId(), role: "assistant", content: text }]
    };
}

const GEM_UA = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36";
const HOME = "https://gemini.google.com/app";
const ENDPOINT = "https://gemini.google.com/_/BardChatUi/data/assistant.lamda.BardFrontendService/StreamGenerate";

const hex = n => crypto.randomBytes(n).toString("hex");
const uuid = () => crypto.randomUUID().toUpperCase();
const reqid = () => Math.floor(Math.random() * 900000) + 100000;

let gemCtx = null;
let gemResume = ["", "", ""];

async function gemBootstrap() {
    try {
        const res = await fetch(HOME, { headers: { "user-agent": GEM_UA, "accept-language": "en-US,en;q=0.9" } });
        const setc = res.headers.getSetCookie?.() || [];
        const cookie = setc.map(c => c.split(";")[0]).join("; ");
        const html = await res.text();

        let bl = (html.match(/"cfb2h":"(.*?)"/) || [])[1] || "";
        if (!bl) bl = (html.match(/"SNlM0e":"(.*?)"/) || [])[1] || "";
        let fsid = (html.match(/"FdrFJe":"(.*?)"/) || [])[1] || "";

        if (!bl || !fsid) {
            const nd = html.match(/<script id="__NEXT_DATA__" type="application\/json">(.*?)<\/script>/);
            if (nd) {
                try {
                    const bard = JSON.parse(nd[1])?.props?.pageProps?.serverState?.BardStateData;
                    if (bard) { bl = bl || bard.cfb2h || bard.SNlM0e || ""; fsid = fsid || bard.FdrFJe || ""; }
                } catch(e) {}
            }
        }
        if (!bl || !fsid) return null;
        gemCtx = { cookie, bl, fsid, uid: uuid() };
        gemResume = ["", "", ""];
        return gemCtx;
    } catch (e) { return null; }
}

function gemBuildBody(message, resume, uid) {
    const inner = [
        [message, 0, null, null, null, null, 0], ["en-US"], resume, "", hex(16),
        null, [1], 1, null, null, 1, 0, null, null, null, null, null, [[0]], 0,
        null, null, null, null, null, null, null, null, 1, null, null, [4],
        null, null, null, null, null, null, null, null, null, null, [2],
        null, null, null, null, null, null, null, null, null, null, null, 0,
        null, null, null, null, null, uid, null, [], null, null, null, null, null, null, 2,
        null, null, null, null, null, null, null, null, null, null, 1
    ];
    return "f.req=" + encodeURIComponent(JSON.stringify([null, JSON.stringify(inner)])) + "&";
}

function gemParseReply(raw) {
    let best = "", cid = null, rid = null, rpid = null;
    for (const line of (raw || "").split("\n")) {
        const s = line.trim();
        if (!s.startsWith('[["wrb.fr"')) continue;
        let outer; try { outer = JSON.parse(s); } catch { continue; }
        for (const row of outer) {
            if (!Array.isArray(row) || row[0] !== "wrb.fr" || typeof row[2] !== "string") continue;
            let body; try { body = JSON.parse(row[2]); } catch { continue; }
            const ids = body[1];
            if (Array.isArray(ids)) {
                if (typeof ids[0] === "string" && ids[0].startsWith("c_")) cid = ids[0];
                if (typeof ids[1] === "string" && ids[1].startsWith("r_")) rid = ids[1];
            }
            const seg = Array.isArray(body[4]) ? body[4][0] : null;
            if (seg) {
                if (seg[0]) rpid = seg[0];
                if (Array.isArray(seg[1])) { const p = seg[1].join(""); if (p.length > best.length) best = p; }
            }
        }
    }
    return { text: best.trim(), cid, rid, rpid };
}

async function geminiChat(prompt) {
    if (!gemCtx) { const ctx = await gemBootstrap(); if (!ctx) throw new Error("Gemini bootstrap failed"); }

    const resume = gemResume[0]
        ? [gemResume[0], gemResume[1], gemResume[2], null, null, null, null, null, null, ""]
        : ["", "", "", null, null, null, null, null, null, ""];

    const url = `${ENDPOINT}?bl=${encodeURIComponent(gemCtx.bl)}&f.sid=${encodeURIComponent(gemCtx.fsid)}&hl=en-US&_reqid=${reqid()}&rt=c`;

    const res = await fetch(url, {
        method: "POST",
        headers: {
            "content-type": "application/x-www-form-urlencoded;charset=UTF-8",
            "user-agent": GEM_UA, "origin": "https://gemini.google.com", "referer": "https://gemini.google.com/",
            "x-same-domain": "1",
            "x-goog-ext-525001261-jspb": JSON.stringify([1, null, null, null, hex(8), null, null, 0, [4, 6], null, null, 1, null, null, 1, null, uuid()]),
            "x-goog-ext-525005358-jspb": JSON.stringify([gemCtx.uid, 1]),
            "x-goog-ext-73010990-jspb": "[0,0,0]", "x-goog-ext-73010989-jspb": "[0]",
            cookie: gemCtx.cookie
        },
        body: gemBuildBody(String(prompt), resume, gemCtx.uid)
    });

    const raw = await res.text();

    if (raw.startsWith("<!DOCTYPE") || raw.startsWith("<html") || raw.startsWith("A server")) {
        gemCtx = null; return geminiChat(prompt);
    }

    const reply = gemParseReply(raw);
    if (!reply.text) { gemCtx = null; return geminiChat(prompt); }
    if (reply.cid) gemResume = [reply.cid, reply.rid || "", reply.rpid || ""];

    const artifacts = [];
    const cleanText = reply.text.replace(/```artifact:([^\n]+)\n([\s\S]*?)```/g, (_, filename, content) => {
        const safeFilename = filename.replace(/[^a-zA-Z0-9.\-_]/g, "").slice(0, 50);
        artifacts.push({ filename: safeFilename, content: content.trim() });
        return `[[ARTIFACT_${artifacts.length - 1}]]`;
    });

    return { ok: true, text: cleanText.trim(), artifacts, resume: [reply.cid || "", reply.rid || "", reply.rpid || ""] };
}

function cleanChallenges() {
    const now = Date.now();
    for (const [k, v] of challenges) {
        if (now - v.ts > 60000) challenges.delete(k);
    }
}

function generateChallenge() {
    const challenge = crypto.randomBytes(16).toString("hex");
    challenges.set(challenge, { ts: Date.now(), solved: false });
    return challenge;
}

function verifyPoW(challenge, nonce) {
    if (typeof nonce !== "string" || nonce.length > 20) return false;
    const hash = crypto.createHash("sha256").update(challenge + nonce).digest("hex");
    return hash.startsWith("0".repeat(POW_DIFFICULTY));
}

function getFingerprint(req) {
    const ip = req.headers["x-forwarded-for"]?.split(",")[0]?.trim() || req.socket?.remoteAddress || "unknown";
    const ua = req.headers["user-agent"] || "";
    const window = Math.floor(Date.now() / 600000);
    return crypto.createHash("sha256").update(`${ip}:${ua}:${window}`).digest("hex").slice(0, 16);
}

function checkRateLimit(fp) {
    const window = Math.floor(Date.now() / 600000);
    const key = `${fp}:${window}`;
    const count = rateLimits.get(key) || 0;
    if (count >= 20) return false;
    rateLimits.set(key, count + 1);
    if (rateLimits.size > 5000) {
        for (const k of rateLimits.keys()) {
            if (!k.endsWith(`:${window}`)) rateLimits.delete(k);
        }
    }
    return true;
}

function blockIP(ip) {
    bannedIPs.add(ip);
    setTimeout(() => bannedIPs.delete(ip), 3600000);
}

function logRequest(ip, path, status) {
    requestLog.push({ ts: Date.now(), ip, path, status });
    if (requestLog.length > MAX_REQUEST_LOG) requestLog.shift();
}

function detectAttack(ip) {
    const recent = requestLog.filter(r => r.ip === ip && Date.now() - r.ts < 60000);
    if (recent.length > 30) { blockIP(ip); return true; }
    return false;
}

module.exports = async function handler(req, res) {
    res.setHeader("Access-Control-Allow-Origin", "*");
    res.setHeader("Access-Control-Allow-Methods", "POST, GET, OPTIONS");
    res.setHeader("Access-Control-Allow-Headers", "Content-Type, X-PoW-Challenge, X-PoW-Nonce");
    res.setHeader("X-Content-Type-Options", "nosniff");
    res.setHeader("X-Frame-Options", "DENY");
    res.setHeader("X-XSS-Protection", "1; mode=block");
    res.setHeader("Referrer-Policy", "strict-origin-when-cross-origin");

    const ip = req.headers["x-forwarded-for"]?.split(",")[0]?.trim() || req.socket?.remoteAddress || "unknown";

    if (bannedIPs.has(ip)) {
        return res.status(403).json({ ok: false, error: "Access denied." });
    }

    if (detectAttack(ip)) {
        return res.status(403).json({ ok: false, error: "Access denied. Too many requests." });
    }

    if (req.method === "OPTIONS") return res.status(200).end();

    if (req.method === "GET") {
        cleanChallenges();
        const challenge = generateChallenge();
        logRequest(ip, "/api/chat?challenge", 200);
        return res.status(200).json({ challenge, difficulty: POW_DIFFICULTY });
    }

    if (req.method !== "POST") {
        logRequest(ip, req.url, 405);
        return res.status(405).json({ error: "Method not allowed" });
    }

    const fp = getFingerprint(req);
    if (!checkRateLimit(fp)) {
        logRequest(ip, "/api/chat", 429);
        return res.status(429).json({ ok: false, error: "Rate limit exceeded." });
    }

    const powChallenge = req.headers["x-pow-challenge"] || (req.body && req.body.powChallenge);
    const powNonce = req.headers["x-pow-nonce"] || (req.body && req.body.powNonce);

    if (!powChallenge || !powNonce) {
        logRequest(ip, "/api/chat", 403);
        return res.status(403).json({ ok: false, error: "PoW required.", needChallenge: true });
    }

    const entry = challenges.get(powChallenge);
    if (!entry) {
        logRequest(ip, "/api/chat", 403);
        return res.status(403).json({ ok: false, error: "Challenge expired.", needChallenge: true });
    }
    if (entry.solved) {
        logRequest(ip, "/api/chat", 403);
        return res.status(403).json({ ok: false, error: "Challenge already used.", needChallenge: true });
    }
    if (!verifyPoW(powChallenge, powNonce)) {
        logRequest(ip, "/api/chat", 403);
        return res.status(403).json({ ok: false, error: "Invalid PoW.", needChallenge: true });
    }
    challenges.set(powChallenge, { ...entry, solved: true });

    try {
        const { prompt, history, webSearch, fileContent, fileName, model } = req.body;

        const sanitizedModel = ALLOWED_MODELS.has(model) ? model : "blackbox";

        if (!prompt && !fileContent) {
            logRequest(ip, "/api/chat", 400);
            return res.status(400).json({ ok: false, error: "Prompt or fileContent required" });
        }

        if (prompt && prompt.length > MAX_PROMPT_LENGTH) {
            logRequest(ip, "/api/chat", 400);
            return res.status(400).json({ ok: false, error: "Prompt too long." });
        }

        if (fileContent && fileContent.length > MAX_FILE_SIZE) {
            logRequest(ip, "/api/chat", 400);
            return res.status(400).json({ ok: false, error: "File too large." });
        }

        let finalPrompt = sanitizeInput(prompt || "");
        if (fileContent) {
            const safeName = fileName ? fileName.replace(/[^a-zA-Z0-9.\-_]/g, "").slice(0, 50) : "file";
            finalPrompt = `[Attached file: ${safeName}]\n\n--- FILE CONTENT ---\n${sanitizeInput(fileContent)}\n--- END ---\n\nUser: ${finalPrompt || "Please analyze this file."}`;
        }

        let result;
        if (sanitizedModel === "gemini") {
            result = await geminiChat(finalPrompt);
        } else {
            result = await blackboxChat(finalPrompt, { history, webSearch });
        }

        logRequest(ip, "/api/chat", 200);
        return res.status(200).json({ ...result, _fp: fp.slice(0, 8) });
    } catch (err) {
        console.error(err);
        logRequest(ip, "/api/chat", 500);
        return res.status(500).json({ ok: false, error: "Internal Server Error" });
    }
};
