const ORIGIN = "https://app.blackbox.ai"
const UA = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/149.0.0.0 Safari/537.36 Edg/149.0.0.0"
const FALLBACK_VALIDATED = "a38f5889-8fef-46d4-8ede-bf4668b6a9bb"
const ANCHOR = /([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})";function detectVscode/

const AGENT_SYSTEM = `You are KRY AI, an advanced intelligent assistant with agent capabilities.

CAPABILITIES:
- You can analyze files, images (with OCR), PDFs, code, and ZIP contents
- You can perform web searches when enabled
- You can generate downloadable files (code, text, JSON, HTML, markdown, CSV)
- You operate as an agent: think step by step, reason through problems, then answer

ARTIFACT / FILE GENERATION:
When the user asks you to create a file, generate code, write a script, or produce any downloadable content — ALWAYS wrap the file content like this:

<artifact filename="example.js" type="javascript">
// your code here
</artifact>

Or for other types:
<artifact filename="data.json" type="json">{"key":"value"}</artifact>
<artifact filename="report.md" type="markdown"># Title</artifact>
<artifact filename="page.html" type="html"><!DOCTYPE html>...</artifact>
<artifact filename="notes.txt" type="text">content here</artifact>

You may have multiple artifacts in one reply. ALWAYS use artifacts for generated files — never just paste raw code without an artifact wrapper when the user wants a downloadable file.

WEB SEARCH:
When web search is enabled, you have access to live internet data. Cite sources when relevant.

OCR / IMAGE ANALYSIS:
When an image is provided, describe it in detail and extract ALL text you can see.

FILE ANALYSIS:
When file contents are provided, analyze them thoroughly.

AGENT BEHAVIOR:
For complex tasks, show your reasoning process. Break down problems. Be thorough.

Wrap your final reply between <answer> and </answer> tags. Write nothing outside these tags.`

const OPEN_TAG = /^(?:<answer>|answer>|nswer>|swer>|wer>|er>|r>|>)\s*/

let cachedValidated = FALLBACK_VALIDATED

function randomId(len = 7) {
  const chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789"
  let s = ""
  for (let i = 0; i < len; i++) s += chars[Math.floor(Math.random() * chars.length)]
  return s
}

function isRejected(raw) {
  return /Generated by BLACKBOX\.AI|not upgraded your account/i.test(raw)
}

function parseAnswer(raw) {
  const think = []
  let body = raw.replace(/<think>([\s\S]*?)<\/think>/g, (_, t) => {
    think.push(t.trim())
    return ""
  })

  // Extract artifacts
  const artifacts = []
  body = body.replace(/<artifact\s+filename="([^"]+)"\s+type="([^"]+)">([\s\S]*?)<\/artifact>/g, (_, filename, type, content) => {
    artifacts.push({ filename, type, content: content.trim() })
    return `\n\n[ARTIFACT:${artifacts.length - 1}]\n\n`
  })

  const end = body.indexOf("</answer>")
  if (end !== -1) body = body.slice(0, end).trimStart().replace(OPEN_TAG, "")
  return {
    text: body.trim(),
    think: think.join("\n\n").trim() || null,
    artifacts
  }
}

async function fetchValidated() {
  const headers = { "user-agent": UA }
  const html = await fetch(`${ORIGIN}/`, { headers }).then(r => r.text()).catch(() => "")
  const chunks = [...new Set([...html.matchAll(/\/_next\/static\/[^"]+\.js/g)].map(m => m[0]))]
  const found = await Promise.all(chunks.map(c =>
    fetch(`${ORIGIN}${c}`, { headers })
      .then(r => r.text())
      .then(js => (js.match(ANCHOR) || [])[1] || null)
      .catch(() => null)
  ))
  return found.find(Boolean) || null
}

function buildPayload(messages, validated, options) {
  const { webSearch = false, agent = "VscodeAgent", maxTokens = 4096 } = options
  return {
    messages,
    id: messages[messages.length - 1].id,
    userSelectedAgent: agent,
    userSelectedModel: null,
    maxTokens,
    validated,
    clickedForceWebSearch: webSearch,
    webSearchModeOption: { autoMode: !webSearch, webMode: webSearch, offlineMode: false },
    codeModelMode: true,
    isPremium: false
  }
}

async function bbRequest(payload) {
  const res = await fetch(`${ORIGIN}/api/chat`, {
    method: "POST",
    headers: {
      "content-type": "application/json",
      "origin": ORIGIN,
      "referer": `${ORIGIN}/chat`,
      "user-agent": UA
    },
    body: JSON.stringify(payload)
  })
  return res.text()
}

async function blackboxChat(prompt, options = {}) {
  const history = Array.isArray(options.history) ? options.history : []
  const userMsg = { id: randomId(), role: "user", content: String(prompt) }
  const wrapped = [{ id: randomId(), role: "system", content: AGENT_SYSTEM }, ...history, userMsg]

  let raw = await bbRequest(buildPayload(wrapped, cachedValidated, options))

  if (isRejected(raw)) {
    const fresh = await fetchValidated()
    if (fresh && fresh !== cachedValidated) {
      cachedValidated = fresh
      raw = await bbRequest(buildPayload(wrapped, cachedValidated, options))
    }
  }

  if (isRejected(raw)) return { ok: false, error: raw.trim() }

  const { text, think, artifacts } = parseAnswer(raw)
  return {
    ok: true,
    text,
    think,
    artifacts,
    history: [...history, userMsg, { id: randomId(), role: "assistant", content: text }]
  }
}

module.exports = async function handler(req, res) {
  res.setHeader("Access-Control-Allow-Origin", "*")
  res.setHeader("Access-Control-Allow-Methods", "POST, OPTIONS")
  res.setHeader("Access-Control-Allow-Headers", "Content-Type")

  if (req.method === "OPTIONS") return res.status(200).end()
  if (req.method !== "POST") return res.status(405).json({ error: "Method not allowed" })

  try {
    const { prompt, history, webSearch, fileContent, fileName, imageData } = req.body

    let finalPrompt = prompt || ""

    // Handle image (OCR)
    if (imageData) {
      finalPrompt = `[IMAGE PROVIDED - Please perform OCR and analyze this image thoroughly. Extract ALL text visible, describe the image content, and answer the user's question.]\n\nUser message: ${prompt || "Please analyze this image and extract any text."}\n\nNote: Image data is provided as base64 but cannot be directly passed in this API integration. Please acknowledge you would analyze the image and provide your best OCR/analysis based on the filename/context.`
    }

    // Handle file content
    if (fileContent) {
      finalPrompt = `[FILE ATTACHED: ${fileName || "uploaded file"}]\n\n--- FILE CONTENT START ---\n${fileContent}\n--- FILE CONTENT END ---\n\nUser question: ${prompt || "Please analyze this file."}`
    }

    if (!finalPrompt.trim()) finalPrompt = prompt || "Hello"

    const result = await blackboxChat(finalPrompt, { history, webSearch })
    return res.status(200).json(result)
  } catch (err) {
    return res.status(500).json({ ok: false, error: err.message })
  }
}
